In [ ]:
import torch
import torch.nn as nn
from torchtyping import TensorType

class Solution:
    def get_dataset(self, positive: List[str], negative: List[str]) -> TensorType[float]:
        # put strings together so we can process each word later
        allStrings = positive + negative
        # define a set to store words
        words = set()
        # process each word from two sentances in the list
        # put them in the set 
        for sentance in allStrings:
            for word in sentance.split():
                words.add(word)
        
        # sort words
        sortedWords = sort(list(words))
        # define a dict to store wordToInt
        wordToInt = {}
        # replace each word to an integer in order
        for index, value in enumerate(sortedWords):
            wordToInt(value) = index + 1
        
        # ???
        return nn.utils.rnn.pad_sequence(wordToInt, batch_first = True)

In [3]:
pip install torch

Note: you may need to restart the kernel to use updated packages.


In [4]:
import torch
import torch.nn as nn
from torchtyping import TensorType

def encode_strings(positive, negative):
    # First let's get the total set of words
    # put strings together so we can process each word later
    words = set()
    combined = positive + negative
    for sentence in combined:
        for word in sentence.split():
            words.add(word)

    # Now let's build a mapping
    sorted_list = sorted(list(words))
    word_to_int = {}
    for i, c in enumerate(sorted_list):
        word_to_int[c] = i + 1

    # Write encode() which is used to build the dataset
    def encode(sentence):
        integers = []
        for word in sentence.split():
            integers.append(word_to_int[word])
        return integers
    
    var_len_tensors = []
    for sentence in combined:
        var_len_tensors.append(torch.tensor(encode(sentence)))
    
    return nn.utils.rnn.pad_sequence(var_len_tensors, batch_first=True)

# Example usage
positive = ["Dogecoin to the moon"]
negative = ["I will short Tesla today"]
result = encode_strings(positive, negative)
print(result)


tensor([[1, 7, 6, 4, 0],
        [2, 9, 5, 3, 8]])


In [6]:
import torch
import torch.nn as nn
from torchtyping import TensorType

def encode_strings(positive, negative):
    # put strings together so we can process each word later
    # define a set to store words
    words = set()
    # process each word from two sentances in the list
    # put them in the set 
    allStrings = positive + negative
    for sentence in allStrings:
        for word in sentence.split():
            words.add(word)

    # sort words and convert them to integers in order
    sorted_list = sorted(list(words))
    wordToInt = {word: i + 1 for i, word in enumerate(sorted_list)}

    # define a function to encode sentences
    def encode(sentence):
        integers = [wordToInt[word] for word in sentence.split()]
        return integers
    
    # Step 4: Encode each sentence and pad the sequences
    var_len_tensors = [torch.tensor(encode(sentence)) for sentence in allStrings]
    padded_tensors = nn.utils.rnn.pad_sequence(var_len_tensors, batch_first=True)
    
    return padded_tensors

# Example usage
positive = ["Dogecoin to the moon"]
negative = ["I will short Tesla today"]
result = encode_strings(positive, negative)
print(result)


tensor([[1, 7, 6, 4, 0],
        [2, 9, 5, 3, 8]])


In [7]:
import torch
import torch.nn as nn

def encode_strings(positive, negative):
    # Collect all unique words and build a mapping from words to integers
    words = set(word for sentence in positive + negative for word in sentence.split())
    word_to_int = {word: i + 1 for i, word in enumerate(sorted(words))}

    # Encode each sentence and pad the sequences
    padded_tensors = nn.utils.rnn.pad_sequence([
        torch.tensor([word_to_int[word] for word in sentence.split()])
        for sentence in positive + negative
    ], batch_first=True)
    
    return padded_tensors

# Example usage
positive = ["Dogecoin to the moon"]
negative = ["I will short Tesla today"]
result = encode_strings(positive, negative)
print(result)


tensor([[1, 7, 6, 4, 0],
        [2, 9, 5, 3, 8]])


In [8]:
positive =["Good case, Excellent value.","Great for the jawbone.","The mic is great.","If you are Razr owner...you must have this!","Highly recommend for any one who has a blue tooth phone"]
negative =["So there is no way for me to plug it in here in the US unless I go buy a converter.","Tied to charger for conversations lasting more than 45 minutes.MAJOR PROBLEMS!!","I have to jiggle the plug to get it to line up right to get decent volume.","Needless to say, I wasted my money.","What a waste of money and time!"]
result = encode_strings(positive, negative)
print(result)

tensor([[ 3, 22,  2, 67,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0],
        [ 4, 27, 59, 37,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0],
        [12, 42, 35, 30,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0],
        [ 7, 73, 19, 10, 52, 47, 32, 61,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0],
        [ 5, 55, 27, 18, 51, 72, 31, 16, 20, 64, 53,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0],
        [11, 60, 35, 49, 71, 27, 41, 63, 54, 36, 34, 33, 34, 59, 14, 65,  6, 29,
         21, 16, 25],
        [13, 63, 23, 27, 24, 39, 46, 58,  1, 43,  9,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0],
        [ 6, 32, 63, 38, 59, 54, 63, 28, 36, 63, 40, 66, 56, 63, 28, 26, 68,  0,
          0,  0,  0],
        [ 8, 63, 57,  6, 70, 48, 45,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0],
        [15, 16, 69, 50, 44, 17, 62,  0,  0,  0,  0,  0,  0,  0,  0,  0, 